version: '3.8'

services:

  storage:
    build: ./storage
    ports:
      - '8090:8090'
    networks:
      - project_network

  reciever:
    build: ./reciever
    ports:
      - "8080:8080"
    networks:
      - project_network

  processing:
    build: ./processing 
    ports:
      - '8100:8100'
    network_mode: host

  audit:
    build: ./audit 
    ports:
      - '8110:8110'
    networks:
      - project_network

volumes:
  db-data:

networks:
  project_network:
