openapi: 3.0.0
info:
  description: This API receives real-time event data from a food delivery service
  version: "1.0.0"
  title: Food delivery
  contact:
    email: rshikder@my.bcit.ca

tags:
  - name: Customer_Order
    description: Any operation that involves or can affect the status or availability of an order

  - name: Proximity
    description: Any operation that deals with the location status of your order

paths:
  /order/status:
    post:
      tags:
        - Customer_Order
      summary: Reports a customer's order
      operationId: app.report_order_status
      description: Adds customer's order
      responses:
        '201':
          description: 'Order received!'
        '400':
          description: 'Invalid input'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderStatus'
    get:
      tags:
        - Customer_Order
      summary: Retrieves a customer's order based on timestamp
      operationId: app.get_order_status
      parameters:
        - name: timestamp
          in: query
          description: Retrieve orders added after this timestamp
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderStatus'
        '400':
          description: Invalid input

  /order/ETA:
    post:
      tags:
        - Proximity
      summary: Reports the expected time of arrival
      operationId: app.reportETA
      description: Calculates the ETA for customer order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderETA'
      responses:
        '201':
          description: ETA calculated successfully
        '400':
          description: Invalid input
    get:
      tags:
        - Proximity
      summary: Retrieves the ETA details based on timestamp
      operationId: app.get_order_ETA
      parameters:
        - name: timestamp
          in: query
          description: Retrieve locations added after this timestamp
          required: false
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of ETAs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderETA'
        '400':
          description: Invalid input
components:
  schemas:
    OrderStatus:
      required:
        - OrderID
        - CustomerAdress
        - timestamp
        - OrderType
        - RestaurantID
        - Tip
        - Customer_PhoneNumber
        - trace_id
      properties:
        OrderID:
          type: string
          example: '7834fhasd7fadsbi'
        CustomerAdress:
          type: string
          example: '123 elm st'
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        OrderType:
          type: string
          example: 'Delivery'
        RestaurantID:
          type: string
          example: 'cvasd8-d8caj-d87r'
        Tip:
          type: integer
          example: 5
        Customer_PhoneNumber:
          type: integer
          example: 7784235023
        trace_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
    OrderETA:
      required:
        - OrderID
        - CustomerLatitude
        - CustomerLongitude
        - RestaurantLatitude
        - RestaurantLongitude
        - DriverLatitude
        - DriverLongitude
        - OrderType
        - Distance
        - timestamp
        - trace_id
      properties:
        OrderID:
          type: integer
          example: 732949
        CustomerLatitude:
          type: integer
          example: 48
        CustomerLongitude:
          type: integer
          example: -123
        RestaurantLatitude:
          type: integer
          example: 49
        RestaurantLongitude:
          type: integer
          example: -123
        DriverLatitude:
          type: integer
          example: 34
        DriverLongitude:
          type: integer
          example: -109
        OrderType:
          type: string
          example: 'Delivery'
        Distance:
          type: integer
          example: 6
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        trace_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90y6-d701748f0851
      type: object